//! Changelog dialog for showing updates after version changes.
//!
//! Release notes are generated by git-cliff (see `cliff.toml`). Each release
//! body has `### Group` section headers ("Features", "Bug Fixes", ...) and
//! bullets shaped like:
//!
//! ```text
//! - **scope:** Subject in [#1234](url) by [@user](url) ([`abc1234`](url))
//! ```
//!
//! Rendered as-is in a TUI the markdown bleeds through (raw `**`, `[text](url)`,
//! backticks, full URLs). We walk the body, track the active group from the
//! `###` headers, peel the scope off the front of each bullet, flatten the
//! inline markdown, and strip the PR / author / commit-hash suffix into
//! structured fields so the popup can render a tidy grouped view.

use crossterm::event::{KeyCode, KeyEvent};
use ratatui::prelude::*;
use ratatui::widgets::*;

use super::DialogResult;
use crate::tui::styles::Theme;
use crate::update::{get_cached_releases, ReleaseInfo};

pub struct ChangelogDialog {
    scroll_offset: usize,
    display_lines: Vec<DisplayLine>,
    dialog_area: Rect,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Category {
    Security,
    Feature,
    BugFix,
    Performance,
    Revert,
    Other,
}

impl Category {
    fn label(self) -> &'static str {
        match self {
            Category::Security => "Security",
            Category::Feature => "Features",
            Category::BugFix => "Bug Fixes",
            Category::Performance => "Performance",
            Category::Revert => "Reverts",
            Category::Other => "Other Changes",
        }
    }

    fn order(self) -> u8 {
        match self {
            Category::Security => 0,
            Category::Feature => 1,
            Category::BugFix => 2,
            Category::Performance => 3,
            Category::Revert => 4,
            Category::Other => 5,
        }
    }
}

#[derive(Debug, Clone)]
struct ChangeItem {
    message: String,
    scope: Option<String>,
    pr_number: Option<u32>,
}

#[derive(Debug, Clone)]
enum DisplayLine {
    NoReleases,
    VersionHeader {
        version: String,
        date: Option<String>,
    },
    Separator,
    NoUserFacingChanges,
    CategoryHeader(Category),
    Item(ChangeItem),
    Empty,
}

impl ChangelogDialog {
    pub fn new(from_version: Option<String>) -> Self {
        let releases = get_cached_releases(from_version.as_deref());
        let display_lines = build_display_lines(&releases);
        Self {
            scroll_offset: 0,
            display_lines,
            dialog_area: Rect::default(),
        }
    }

    /// A click anywhere inside the changelog dialog dismisses it,
    /// matching the keyboard's "any of Enter/Esc/q/Space submits"
    /// model. Returns None for clicks outside so the caller can decide
    /// whether to swallow them.
    pub fn handle_click(&self, col: u16, row: u16) -> Option<DialogResult<()>> {
        if self
            .dialog_area
            .contains(ratatui::layout::Position::from((col, row)))
        {
            Some(DialogResult::Submit(()))
        } else {
            None
        }
    }

    pub fn handle_key(&mut self, key: KeyEvent) -> DialogResult<()> {
        let max_scroll = self.display_lines.len().saturating_sub(1);

        match key.code {
            KeyCode::Enter | KeyCode::Esc | KeyCode::Char('q') | KeyCode::Char(' ') => {
                DialogResult::Submit(())
            }
            KeyCode::Down | KeyCode::Char('j') => {
                if self.scroll_offset < max_scroll {
                    self.scroll_offset += 1;
                }
                DialogResult::Continue
            }
            KeyCode::Up | KeyCode::Char('k') => {
                self.scroll_offset = self.scroll_offset.saturating_sub(1);
                DialogResult::Continue
            }
            KeyCode::PageDown => {
                self.scroll_offset = (self.scroll_offset + 5).min(max_scroll);
                DialogResult::Continue
            }
            KeyCode::PageUp => {
                self.scroll_offset = self.scroll_offset.saturating_sub(5);
                DialogResult::Continue
            }
            KeyCode::Home => {
                self.scroll_offset = 0;
                DialogResult::Continue
            }
            KeyCode::End => {
                self.scroll_offset = max_scroll;
                DialogResult::Continue
            }
            _ => DialogResult::Continue,
        }
    }

    pub fn render(&mut self, frame: &mut Frame, area: Rect, theme: &Theme) {
        let dialog_width = (area.width * 80 / 100).clamp(60, 100);
        let dialog_height = (area.height * 80 / 100).clamp(16, 40);
        let dialog_area = super::centered_rect(area, dialog_width, dialog_height);
        self.dialog_area = dialog_area;

        frame.render_widget(Clear, dialog_area);

        let block = Block::default()
            .borders(Borders::ALL)
            .border_type(BorderType::Rounded)
            .border_style(Style::default().fg(theme.accent))
            .title(" What's New ")
            .title_style(Style::default().fg(theme.accent).bold());

        let inner = block.inner(dialog_area);
        frame.render_widget(block, dialog_area);

        let chunks = Layout::default()
            .direction(Direction::Vertical)
            .margin(1)
            .constraints([Constraint::Min(1), Constraint::Length(2)])
            .split(inner);

        let content_area = chunks[0];
        let visible_height = content_area.height as usize;
        let separator_width = (content_area.width as usize).min(60);

        let styled: Vec<Line> = self
            .display_lines
            .iter()
            .skip(self.scroll_offset)
            .take(visible_height)
            .map(|line| render_line(line, theme, separator_width))
            .collect();

        let paragraph = Paragraph::new(styled).wrap(Wrap { trim: false });
        frame.render_widget(paragraph, content_area);

        let total = self.display_lines.len();
        let scroll_hint = if total > visible_height {
            format!(
                "  j/k scroll  ({}/{})",
                (self.scroll_offset + visible_height).min(total),
                total
            )
        } else {
            "  j/k scroll".to_string()
        };

        let button = Line::from(vec![
            Span::styled("[Got it]", Style::default().fg(theme.accent).bold()),
            Span::styled(scroll_hint, Style::default().fg(theme.dimmed)),
        ]);
        frame.render_widget(
            Paragraph::new(button).alignment(Alignment::Center),
            chunks[1],
        );
    }
}

fn render_line<'a>(line: &DisplayLine, theme: &Theme, separator_width: usize) -> Line<'a> {
    match line {
        DisplayLine::NoReleases => Line::from(Span::styled(
            "No release notes available.",
            Style::default().fg(theme.dimmed),
        )),
        DisplayLine::VersionHeader { version, date } => {
            let mut spans = vec![Span::styled(
                format!("v{}", version),
                Style::default().fg(theme.title).bold(),
            )];
            if let Some(date) = date {
                spans.push(Span::styled(
                    format!("  {}", date),
                    Style::default().fg(theme.dimmed),
                ));
            }
            Line::from(spans)
        }
        DisplayLine::Separator => Line::from(Span::styled(
            "─".repeat(separator_width.max(1)),
            Style::default().fg(theme.dimmed),
        )),
        DisplayLine::NoUserFacingChanges => Line::from(Span::styled(
            "  (no user-facing changes in this release)",
            Style::default().fg(theme.dimmed),
        )),
        DisplayLine::CategoryHeader(cat) => Line::from(Span::styled(
            cat.label(),
            Style::default().fg(theme.accent).bold(),
        )),
        DisplayLine::Item(item) => {
            let mut spans: Vec<Span<'a>> =
                vec![Span::styled("  • ", Style::default().fg(theme.dimmed))];
            if let Some(scope) = &item.scope {
                spans.push(Span::styled(
                    format!("{}: ", scope),
                    Style::default().fg(theme.hint),
                ));
            }
            spans.push(Span::styled(
                capitalize_first(&item.message),
                Style::default().fg(theme.text),
            ));
            if let Some(pr) = item.pr_number {
                spans.push(Span::styled(
                    format!(" (#{})", pr),
                    Style::default().fg(theme.dimmed),
                ));
            }
            Line::from(spans)
        }
        DisplayLine::Empty => Line::from(""),
    }
}

fn build_display_lines(releases: &[ReleaseInfo]) -> Vec<DisplayLine> {
    let mut lines = Vec::new();

    if releases.is_empty() {
        lines.push(DisplayLine::NoReleases);
        return lines;
    }

    for (idx, release) in releases.iter().enumerate() {
        if idx > 0 {
            lines.push(DisplayLine::Empty);
        }

        let date = release
            .published_at
            .as_deref()
            .and_then(|s| s.split('T').next())
            .map(str::to_owned);

        lines.push(DisplayLine::VersionHeader {
            version: release.version.clone(),
            date,
        });
        lines.push(DisplayLine::Separator);
        lines.push(DisplayLine::Empty);

        let groups = parse_release_body(&release.body);
        if groups.is_empty() {
            lines.push(DisplayLine::NoUserFacingChanges);
            continue;
        }

        for (i, (category, items)) in groups.into_iter().enumerate() {
            if i > 0 {
                lines.push(DisplayLine::Empty);
            }
            lines.push(DisplayLine::CategoryHeader(category));
            for item in items {
                lines.push(DisplayLine::Item(item));
            }
        }
    }

    lines
}

fn parse_release_body(body: &str) -> Vec<(Category, Vec<ChangeItem>)> {
    let mut by_category: std::collections::BTreeMap<u8, (Category, Vec<ChangeItem>)> =
        Default::default();
    let mut current_group: Option<Category> = None;

    for raw in body.lines() {
        let trimmed = raw.trim();

        // git-cliff emits "### Features" / "### Bug Fixes" / etc. Match those
        // first so the prefix check below (which also catches "## ") doesn't
        // swallow them.
        if let Some(rest) = trimmed.strip_prefix("### ") {
            current_group = group_label_to_category(rest.trim());
            continue;
        }
        // The version header ("## [1.8.0](url) - date") and any stray ## blocks
        // reset the active group.
        if trimmed.starts_with("## ") {
            current_group = None;
            continue;
        }

        // Real markdown bullets only — anything else (headers, the
        // "**Full Changelog**: ..." footer, blank lines) is noise.
        let bullet = if let Some(rest) = trimmed.strip_prefix("- ") {
            rest.trim()
        } else if let Some(rest) = trimmed.strip_prefix("* ") {
            rest.trim()
        } else {
            continue;
        };

        // git-cliff renders the "New Contributors" roster as bullets too;
        // skip them whether or not their `###` header was recognized.
        if bullet.contains("made their first contribution") {
            continue;
        }

        // Peel scope off the front before flattening so an inline colon
        // somewhere in the subject can't be mistaken for the scope separator.
        let (scope, content) = strip_bold_scope_prefix(bullet);
        let content = flatten_markdown(&content);
        let (message, pr_number) = strip_attribution(&content);

        let category = current_group.unwrap_or(Category::Other);
        let item = ChangeItem {
            message,
            scope,
            pr_number,
        };
        by_category
            .entry(category.order())
            .or_insert_with(|| (category, Vec::new()))
            .1
            .push(item);
    }

    by_category.into_values().collect()
}

fn group_label_to_category(label: &str) -> Option<Category> {
    match label {
        "Features" => Some(Category::Feature),
        "Bug Fixes" => Some(Category::BugFix),
        "Performance" => Some(Category::Performance),
        "Security" => Some(Category::Security),
        "Reverts" => Some(Category::Revert),
        "Other" => Some(Category::Other),
        // "New Contributors" and any future group we don't recognize land
        // here. Bullets that follow will get current_group = None and fall
        // into the catch-all path below the loop.
        _ => None,
    }
}

/// Strip a leading `**scope:** ` (the bold-prefix git-cliff emits when a
/// commit has a scope). Returns the scope (if matched) and the rest of the
/// bullet with the bold prefix removed.
fn strip_bold_scope_prefix(bullet: &str) -> (Option<String>, String) {
    let rest = match bullet.strip_prefix("**") {
        Some(r) => r,
        None => return (None, bullet.to_string()),
    };
    let close = match rest.find(":**") {
        Some(i) => i,
        None => return (None, bullet.to_string()),
    };
    let scope = rest[..close].trim().to_string();
    if scope.is_empty() {
        return (None, bullet.to_string());
    }
    let after = rest[close + 3..].trim_start().to_string();
    (Some(scope), after)
}

/// Replace markdown `[text](url)` with `text`, then drop `**` bold markers and
/// inline-code backticks. Just enough to collapse a git-cliff bullet into
/// plain text — not a real markdown renderer.
fn flatten_markdown(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut chars = s.chars().peekable();
    while let Some(c) = chars.next() {
        if c != '[' {
            out.push(c);
            continue;
        }
        let mut text = String::new();
        let mut closed = false;
        for nc in chars.by_ref() {
            if nc == ']' {
                closed = true;
                break;
            }
            text.push(nc);
        }
        if !closed {
            out.push('[');
            out.push_str(&text);
            continue;
        }
        if chars.peek() != Some(&'(') {
            out.push('[');
            out.push_str(&text);
            out.push(']');
            continue;
        }
        chars.next();
        let mut url_closed = false;
        for nc in chars.by_ref() {
            if nc == ')' {
                url_closed = true;
                break;
            }
        }
        if !url_closed {
            out.push_str(&text);
            continue;
        }
        out.push_str(&text);
    }
    out.replace("**", "").replace('`', "")
}

/// Pull the PR number out of the trailing ` in #N by @user (hash)` attribution
/// and return the bare message. Trailing parenthesized content is only stripped
/// when it looks like a short commit hash; legitimate `(parenthetical)`s in the
/// subject survive.
fn strip_attribution(line: &str) -> (String, Option<u32>) {
    let mut working = line.to_string();
    let mut pr_number: Option<u32> = None;

    if let Some(idx) = working.rfind(" in #") {
        let after = &working[idx + 5..];
        let digits: String = after.chars().take_while(|c| c.is_ascii_digit()).collect();
        if let Ok(n) = digits.parse::<u32>() {
            pr_number = Some(n);
            working.truncate(idx);
        }
    }

    if let Some(by_idx) = working.rfind(" by @") {
        working.truncate(by_idx);
    }

    let trimmed = working.trim_end();
    working = strip_trailing_hash_paren(trimmed)
        .unwrap_or(trimmed)
        .to_string();

    (working.trim().to_string(), pr_number)
}

/// If `s` ends with ` (xxxxxxx)` where the inside is a short hex commit hash,
/// return the slice without it. Returns `None` for anything else, including
/// legitimate parenthetical content like `(workaround)`.
fn strip_trailing_hash_paren(s: &str) -> Option<&str> {
    let inner = s.strip_suffix(')')?;
    let open = inner.rfind(" (")?;
    let inside = &inner[open + 2..];
    if inside.is_empty() || inside.len() > 40 || !inside.chars().all(|c| c.is_ascii_hexdigit()) {
        return None;
    }
    Some(&inner[..open])
}

fn capitalize_first(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        Some(c) => c.to_uppercase().chain(chars).collect(),
        None => String::new(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crossterm::event::KeyModifiers;

    fn key(code: KeyCode) -> KeyEvent {
        KeyEvent::new(code, KeyModifiers::NONE)
    }

    fn dialog_with(lines: Vec<DisplayLine>) -> ChangelogDialog {
        ChangelogDialog {
            scroll_offset: 0,
            display_lines: lines,
            dialog_area: Rect::default(),
        }
    }

    #[test]
    fn submit_keys_close_dialog() {
        for code in [
            KeyCode::Enter,
            KeyCode::Esc,
            KeyCode::Char('q'),
            KeyCode::Char(' '),
        ] {
            let mut dialog = dialog_with(vec![DisplayLine::NoReleases]);
            assert!(matches!(
                dialog.handle_key(key(code)),
                DialogResult::Submit(())
            ));
        }
    }

    #[test]
    fn scroll_down_advances_within_bounds() {
        let mut dialog = dialog_with(vec![
            DisplayLine::VersionHeader {
                version: "1.0.0".into(),
                date: None,
            },
            DisplayLine::Separator,
            DisplayLine::Empty,
            DisplayLine::Item(ChangeItem {
                message: "x".into(),
                scope: None,
                pr_number: None,
            }),
        ]);
        for _ in 0..10 {
            dialog.handle_key(key(KeyCode::Down));
        }
        assert_eq!(dialog.scroll_offset, dialog.display_lines.len() - 1);
    }

    #[test]
    fn scroll_up_clamps_to_zero() {
        let mut dialog = dialog_with(vec![DisplayLine::NoReleases]);
        dialog.scroll_offset = 0;
        dialog.handle_key(key(KeyCode::Up));
        assert_eq!(dialog.scroll_offset, 0);
    }

    #[test]
    fn home_end_jump_to_extremes() {
        let mut dialog = dialog_with(vec![
            DisplayLine::Empty,
            DisplayLine::Empty,
            DisplayLine::Empty,
        ]);
        dialog.handle_key(key(KeyCode::End));
        assert_eq!(dialog.scroll_offset, 2);
        dialog.handle_key(key(KeyCode::Home));
        assert_eq!(dialog.scroll_offset, 0);
    }

    #[test]
    fn empty_releases_emits_placeholder() {
        let lines = build_display_lines(&[]);
        assert_eq!(lines.len(), 1);
        assert!(matches!(lines[0], DisplayLine::NoReleases));
    }

    #[test]
    fn strip_attribution_extracts_pr_number() {
        let (msg, pr) = strip_attribution(
            "De-flake live ensure-session-restart status check in #1249 by @Seluj78 (39d4b40)",
        );
        assert_eq!(msg, "De-flake live ensure-session-restart status check");
        assert_eq!(pr, Some(1249));
    }

    #[test]
    fn strip_attribution_handles_no_attribution() {
        let (msg, pr) = strip_attribution("Some PR title without attribution");
        assert_eq!(msg, "Some PR title without attribution");
        assert_eq!(pr, None);
    }

    #[test]
    fn strip_attribution_preserves_subject_parentheticals() {
        // git-cliff appends ` (<hash>)` for the short commit SHA. Hex-only
        // contents trigger the trailing-paren strip; anything else should
        // survive so commits like "feat: foo (workaround)" don't get truncated.
        let (msg, pr) = strip_attribution("foo (workaround) in #7 by @user (abc1234)");
        assert_eq!(msg, "foo (workaround)");
        assert_eq!(pr, Some(7));
    }

    #[test]
    fn strip_bold_scope_prefix_extracts_scope() {
        let (scope, rest) = strip_bold_scope_prefix("**cockpit:** Restore something");
        assert_eq!(scope.as_deref(), Some("cockpit"));
        assert_eq!(rest, "Restore something");
    }

    #[test]
    fn strip_bold_scope_prefix_handles_multi_part_scope() {
        let (scope, rest) =
            strip_bold_scope_prefix("**cockpit/ws:** Restore drop-cancels-reader semantics");
        assert_eq!(scope.as_deref(), Some("cockpit/ws"));
        assert_eq!(rest, "Restore drop-cancels-reader semantics");
    }

    #[test]
    fn strip_bold_scope_prefix_returns_none_when_no_bold() {
        let (scope, rest) = strip_bold_scope_prefix("Force color for Antigravity launches");
        assert!(scope.is_none());
        assert_eq!(rest, "Force color for Antigravity launches");
    }

    #[test]
    fn flatten_markdown_collapses_links_bold_and_code() {
        let input = "**scope:** subj in [#1249](https://x/y/pull/1249) by [@u](https://x/u) ([`abc1234`](https://x/c/abc))";
        assert_eq!(
            flatten_markdown(input),
            "scope: subj in #1249 by @u (abc1234)"
        );
    }

    #[test]
    fn flatten_markdown_leaves_orphan_brackets_alone() {
        // Malformed links (no url) survive as plain text so the bullet stays
        // readable.
        assert_eq!(
            flatten_markdown("plain [text] no url"),
            "plain [text] no url"
        );
    }

    #[test]
    fn parse_release_body_groups_by_section_header() {
        let body = "\
## [1.8.0](https://github.com/o/r/releases/tag/v1.8.0) - 2026-05-22

### Bug Fixes

- **test:** De-flake status check in [#1249](https://github.com/o/r/pull/1249) by [@Seluj78](https://github.com/Seluj78) ([`39d4b40`](https://github.com/o/r/commit/39d4b40))
- Force color for Antigravity launches in [#1382](https://github.com/o/r/pull/1382) by [@MovieHolic-Plex](https://github.com/MovieHolic-Plex) ([`e2c9a02`](https://github.com/o/r/commit/e2c9a02))

### Features

- **tui:** Full-screen multi-column help overlay in [#1410](https://github.com/o/r/pull/1410) by [@njbrake](https://github.com/njbrake) ([`4ceed86`](https://github.com/o/r/commit/4ceed86))

### Other

- Loose change with no scope in [#999](https://github.com/o/r/pull/999) by [@nobody](https://github.com/nobody) ([`deadbee`](https://github.com/o/r/commit/deadbee))

### New Contributors

- [@flyinghail](https://github.com/flyinghail) made their first contribution in [#1234](https://github.com/o/r/pull/1234)

**Full Changelog**: https://github.com/o/r/compare/v1.7.1...v1.8.0
";

        let groups = parse_release_body(body);
        let labels: Vec<_> = groups.iter().map(|(c, _)| c.label()).collect();
        assert_eq!(labels, ["Features", "Bug Fixes", "Other Changes"]);

        let features = &groups[0].1;
        assert_eq!(features.len(), 1);
        assert_eq!(features[0].scope.as_deref(), Some("tui"));
        assert_eq!(features[0].message, "Full-screen multi-column help overlay");
        assert_eq!(features[0].pr_number, Some(1410));

        let fixes = &groups[1].1;
        assert_eq!(fixes.len(), 2);
        assert_eq!(fixes[0].scope.as_deref(), Some("test"));
        assert_eq!(fixes[0].message, "De-flake status check");
        assert_eq!(fixes[0].pr_number, Some(1249));
        assert!(fixes[1].scope.is_none());
        assert_eq!(fixes[1].message, "Force color for Antigravity launches");
        assert_eq!(fixes[1].pr_number, Some(1382));

        let other = &groups[2].1;
        assert_eq!(other.len(), 1);
        assert_eq!(other[0].message, "Loose change with no scope");
        assert_eq!(other[0].pr_number, Some(999));
    }

    #[test]
    fn parse_release_body_handles_release_with_no_visible_groups() {
        // git-cliff hides chore/build/ci/docs/style/refactor/test via skip
        // rules in cliff.toml, so a release that only had those produces a
        // body with just the version header and footer — no `### Group`
        // sections, no bullets.
        let body = "\
## [1.0.1](https://github.com/o/r/releases/tag/v1.0.1) - 2026-05-19


**Full Changelog**: https://github.com/o/r/compare/v1.0.0...v1.0.1
";
        let groups = parse_release_body(body);
        assert!(groups.is_empty());
    }

    #[test]
    fn build_display_lines_marks_no_user_facing_changes() {
        let release = ReleaseInfo {
            version: "1.0.1".into(),
            body: "## [1.0.1](https://x/y/releases/tag/v1.0.1) - 2026-05-19\n\n**Full Changelog**: https://x/y/compare/v1.0.0...v1.0.1\n".into(),
            published_at: Some("2026-05-19T10:00:00Z".into()),
        };
        let lines = build_display_lines(std::slice::from_ref(&release));
        // VersionHeader, Separator, Empty, NoUserFacingChanges.
        assert_eq!(lines.len(), 4);
        match &lines[0] {
            DisplayLine::VersionHeader { version, date } => {
                assert_eq!(version, "1.0.1");
                assert_eq!(date.as_deref(), Some("2026-05-19"));
            }
            _ => panic!("expected version header first"),
        }
        assert!(matches!(
            lines.last().unwrap(),
            DisplayLine::NoUserFacingChanges
        ));
    }

    #[test]
    fn build_display_lines_renders_multiple_releases() {
        let releases = vec![
            ReleaseInfo {
                version: "1.1.0".into(),
                body: "### Features\n- **tui:** shiny in [#10](https://x/y/pull/10) by [@x](https://x/x) ([`aaaaaaa`](https://x/y/commit/aaaaaaa))\n".into(),
                published_at: Some("2026-05-19T00:00:00Z".into()),
            },
            ReleaseInfo {
                version: "1.0.1".into(),
                body: "### Bug Fixes\n- **web:** bug in [#5](https://x/y/pull/5) by [@y](https://x/y) ([`bbbbbbb`](https://x/y/commit/bbbbbbb))\n".into(),
                published_at: None,
            },
        ];
        let lines = build_display_lines(&releases);
        let version_headers: Vec<_> = lines
            .iter()
            .filter_map(|l| match l {
                DisplayLine::VersionHeader { version, .. } => Some(version.as_str()),
                _ => None,
            })
            .collect();
        assert_eq!(version_headers, ["1.1.0", "1.0.1"]);

        let category_headers: Vec<_> = lines
            .iter()
            .filter_map(|l| match l {
                DisplayLine::CategoryHeader(c) => Some(c.label()),
                _ => None,
            })
            .collect();
        assert_eq!(category_headers, ["Features", "Bug Fixes"]);
    }

    #[test]
    fn capitalize_first_capitalizes_only_the_first_char() {
        assert_eq!(capitalize_first("add feature"), "Add feature");
        assert_eq!(capitalize_first(""), "");
        assert_eq!(capitalize_first("a"), "A");
        assert_eq!(capitalize_first("Already"), "Already");
    }
}
